<a href="https://colab.research.google.com/github/minniewithane/linkedin-learning/blob/main/Using_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd with tensors

In [1]:
import torch

In [6]:
w = torch.randn(4, 3, requires_grad=True)
w

tensor([[-0.2645,  1.8793,  1.1813],
        [ 0.4456,  1.3343,  2.4019],
        [ 0.1549,  0.4787, -0.7273],
        [-0.7036,  1.8591, -0.0081]], requires_grad=True)

In [8]:
w.requires_grad_(False)

tensor([[-0.2645,  1.8793,  1.1813],
        [ 0.4456,  1.3343,  2.4019],
        [ 0.1549,  0.4787, -0.7273],
        [-0.7036,  1.8591, -0.0081]])

In [9]:
w.requires_grad_(True)

tensor([[-0.2645,  1.8793,  1.1813],
        [ 0.4456,  1.3343,  2.4019],
        [ 0.1549,  0.4787, -0.7273],
        [-0.7036,  1.8591, -0.0081]], requires_grad=True)

In [12]:
y = torch.exp(w)
print(y)

tensor([[ 0.7676,  6.5488,  3.2587],
        [ 1.5614,  3.7972, 11.0442],
        [ 1.1676,  1.6140,  0.4832],
        [ 0.4948,  6.4177,  0.9919]], grad_fn=<ExpBackward0>)


In [14]:
output = y.mean()

In [15]:
print(w.grad)

None


In [16]:
output.backward()

In [17]:
print(w.grad)

tensor([[0.0640, 0.5457, 0.2716],
        [0.1301, 0.3164, 0.9203],
        [0.0973, 0.1345, 0.0403],
        [0.0412, 0.5348, 0.0827]])


In [19]:
print(output.requires_grad)

True


In [21]:
with torch.no_grad():
    output = (w+y).mean()
    print(w.requires_grad)

True
